var namespace_osiris_i =
[
    [ "Events", "namespace_osiris_i_1_1_events.html", "namespace_osiris_i_1_1_events" ],
    [ "Graphics", "namespace_osiris_i_1_1_graphics.html", "namespace_osiris_i_1_1_graphics" ],
    [ "Interfaces", "namespace_osiris_i_1_1_interfaces.html", "namespace_osiris_i_1_1_interfaces" ],
    [ "Manager", "namespace_osiris_i_1_1_manager.html", "namespace_osiris_i_1_1_manager" ],
    [ "Memory", "namespace_osiris_i_1_1_memory.html", "namespace_osiris_i_1_1_memory" ],
    [ "Networking", "namespace_osiris_i_1_1_networking.html", "namespace_osiris_i_1_1_networking" ],
    [ "Resources", "namespace_osiris_i_1_1_resources.html", "namespace_osiris_i_1_1_resources" ],
    [ "Threading", "namespace_osiris_i_1_1_threading.html", "namespace_osiris_i_1_1_threading" ],
    [ "Utilities", "namespace_osiris_i_1_1_utilities.html", "namespace_osiris_i_1_1_utilities" ],
    [ "Converter", "class_osiris_i_1_1_converter.html", null ],
    [ "IOsirisObject", "class_osiris_i_1_1_i_osiris_object.html", "class_osiris_i_1_1_i_osiris_object" ],
    [ "OsirisIDevice", "class_osiris_i_1_1_osiris_i_device.html", "class_osiris_i_1_1_osiris_i_device" ],
    [ "UV_Coordinates", "struct_osiris_i_1_1_u_v___coordinates.html", "struct_osiris_i_1_1_u_v___coordinates" ],
    [ "Rectangle", "struct_osiris_i_1_1_rectangle.html", "struct_osiris_i_1_1_rectangle" ],
    [ "OVector2", "struct_osiris_i_1_1_o_vector2.html", "struct_osiris_i_1_1_o_vector2" ],
    [ "OVector3", "struct_osiris_i_1_1_o_vector3.html", "struct_osiris_i_1_1_o_vector3" ],
    [ "OVector4", "struct_osiris_i_1_1_o_vector4.html", "struct_osiris_i_1_1_o_vector4" ],
    [ "OMatrix4x4", "struct_osiris_i_1_1_o_matrix4x4.html", "struct_osiris_i_1_1_o_matrix4x4" ],
    [ "OVertex", "struct_osiris_i_1_1_o_vertex.html", "struct_osiris_i_1_1_o_vertex" ],
    [ "OFace", "struct_osiris_i_1_1_o_face.html", "struct_osiris_i_1_1_o_face" ],
    [ "MatrixBufferType", "struct_osiris_i_1_1_matrix_buffer_type.html", "struct_osiris_i_1_1_matrix_buffer_type" ],
    [ "PixelBufferType", "struct_osiris_i_1_1_pixel_buffer_type.html", "struct_osiris_i_1_1_pixel_buffer_type" ],
    [ "DiffuseLightBufferType", "struct_osiris_i_1_1_diffuse_light_buffer_type.html", "struct_osiris_i_1_1_diffuse_light_buffer_type" ],
    [ "AmbientLightBufferType", "struct_osiris_i_1_1_ambient_light_buffer_type.html", "struct_osiris_i_1_1_ambient_light_buffer_type" ],
    [ "ComponentMapping", "struct_osiris_i_1_1_component_mapping.html", "struct_osiris_i_1_1_component_mapping" ],
    [ "NetworkFrame", "struct_osiris_i_1_1_network_frame.html", "struct_osiris_i_1_1_network_frame" ]
];